package com.smarthome.monitor.core.ui.theme

// core/ui/theme — Material 3 theme.
// Week 1: Color.kt, Theme.kt, Type.kt (generated by the Android Studio wizard
// are moved/copied here). Touched once, never again.
